name: sco_proj_1
description: "Security research demo Flutter project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.0
  cloud_functions: ^5.2.0
  firebase_app_check: ^0.3.0+7
  get_it: ^7.7.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  flutter_jailbreak_detection: ^1.10.0
  crypto: ^3.0.5
  x509: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/mock_config.json
